apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: mongo-operator-cluster-role
  namespace: bm-cz
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "get", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]  # TODO: Remove list access to secrets.
  verbs: ["list", "get", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["get", "create"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["watch", "list"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["list", "get", "create", "patch", "delete", "watch"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "create"]
- apiGroups: ["operators.javamachr.cz"]
  resources: ["mongos"]
  verbs: ["list", "get", "watch"]
