apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-operator
  name: mongo-operator
  namespace: bm-cz
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: mongo-operator
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: mongo-operator
    spec:
      containers:
      - image: docker-registry.default.svc:5000/base-images/k8s-mongo-operator:1.0.0
        imagePullPolicy: Always
        name: mongo-operator
        env:
        - name: LOGGING_LEVEL
          value: INFO
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        volumeMounts:
          - name: backup-data
            mountPath: /data
      serviceAccount: mongo-operator-service-account
      volumes:
        - name: backup-data
          persistentVolumeClaim:
            claimName: pvc-bmcz-mongobck
