apiVersion: "operators.javamachr.cz/v1"
kind: Mongo
metadata:
  name: mongo-cluster
  namespace: mongo-operator-cluster
  labels:
    app: mongo-cluster
spec:
  mongodb:
    replicas: 3  # Must be between 3 and 50
    cpu_limit: "200m"
    memory_limit: "64Mi"
  users:
    admin_password: admin
    user_name: webapp
    user_password: passwd1
    databasename: fortunaweb
  backups:
    cron: "0 * * * *"  # every hour at 0 minutes
    restore_from: mongodb-backup-default-mongo-cluster-2019-02-07_132931.archive.gz
